### PR TITLE
latest release

### PR DESCRIPTION
**Pull request by markcollister**

### CODE REVIEW

**Comment by markcollister** [comment]
latest release

**Comment by szepeviktor** [comment]
@markcollister The changelog contains an unreleased version.

image

**Comment by szepeviktor** [comment]
NO! 1.10.1 contains "1.10.0" 💥

https://plugins.trac.wordpress.org/browser/smtp2go/tags/1.10.1/smtp2go-wordpress-plugin.php#L18

**Comment by markcollister** [comment]
Thanks @szepeviktor , my plugin deploy process broke mid deploy of the previous version. I got half a fix up, but have noted the issue you mention and am releasing again early next week

**Pull request merged**
